package icons

var (
	RightArrow   = "➜"
	RightPointer = "▶"
	LeftPointer  = "◀"
	UpPointer    = "▲"
	DownPointer  = "▼"
	Check        = "✓"
	Cross        = "✗"
	Warning      = "⚠"
	Info         = "i"
	CircleEmpty  = "○"
	CircleFilled = "●"
	CircleCheck  = "◉"
	Star         = "★"
	Bullet       = "•"
	Heart        = "❤"
	Flag         = "⚑"
	Lightning    = "⚡"
	Globe        = "🌐"
	Key          = "🔑"
	Arrow        = "➜"
	Clock        = "🕒"
)
